#!/usr/bin/expect -f

if {$argc < 3} {
    send_user "Usage: $argv0 user host pass\n"
    exit 1
}

set user [lindex $argv 0]
set host [lindex $argv 1]
set pass [lindex $argv 2]

system "rm -rf ~/.ssh/known_hosts"
# ssh romete machine, execute CMD
spawn ssh -F /dev/null -o PubkeyAuthentication=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=10 -o StrictHostKeyChecking=no "$user@$host" "CMD"
expect {
    "yes/no" { send "yes\r"; exp_continue }
    "*assword*" { send "$pass\r"; }
    eof {send_user "Error to connect $user@$host"; exit 3;}
}
expect {
    "*assword*" {send_user "Error password"; exit 2}
    eof ;
}

exit 0
